baseURL = "https://www.neldeles.com/"
languageCode = "en-us"
title = "neldeles.com"
theme = "hugo-theme-cactus-plus"

[params]
	author = "Noel Deles"
	description = "My personal time capsule"
	bio = ""

	twitter = "neldeles"
	facebook = "neldeles"

	enableRSS = false
	enableToc = true

	enableDisqus = true
	disqusShortname = "neldeles"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false


	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""


	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = "Posts"
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/neldeles"
	twitter-square = "https://www.twitter.com/neldeles"
	github-square = "https://www.github.com/neldeles"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url  = "/articles/"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 20
  
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 30

  [[menu.main]]
    name = "Tutorials"
    url  = "/tutorials/"
    weight = 100

