baseURL = "https://www.neldeles.com/"
languageCode = "en-us"
title = "neldeles.com"
theme = "hugo-paper"

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

 [[menu.main]]
  name = "Blog"
  url  = "blog/"
  weight = 10
