baseURL = "https://www.neldeles.com/"
languageCode = "en-us"
title = "neldeles.com"
theme = "hugo-paper"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url  = "/articles/"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 20
  
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 30

  [[menu.main]]
    name = "Tutorials"
    url  = "/tutorials/"
    weight = 100

